### ISSUE TITLE
Knative RabbitMQ broker not generating URL.

### ISSUE THREAD

**Issue by andersonsoares-tomtom** [knative-sandbox/eventing-rabbitmq#526] opened 2021-11-25 13:29 UTC
**Describe the bug**
Rabbitmq broker do not generate URL.
```
soareslo:~$kubectl get brokers
NAME             URL                                                                                AGE    READY   REASON
lasbroker        http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/lasbroker   7d2h   True    
rabbitmqbroker                                                                                      46m 
```

 **Expected behavior**
Generate URL like Kafka Broker generated.

 **To Reproduce**
I'm trying to create a RabbitMQ broker to use against my Azure Service bus.
So, I have done the following,:
I used this docs `https://knative.dev/development/eventing/broker/rabbitmq-broker/`
and this one as well `https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/standalone.md`

So I have the following:
I have Kafka broker configured and working nicely.
However now I want to add the RabbitMQ broker as well.

So I installed the RabbitMQ broker via:
`kubectl apply -f https://storage.googleapis.com/knative-nightly/eventing-rabbitmq/latest/rabbitmq-broker.yaml`

soareslo:~$kubectl get deployment.apps -n knative-eventing 

```
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE

eventing-controller          1/1     1            1           7d1h

eventing-webhook             1/1     1            1           7d1h

kafka-broker-dispatcher      1/1     1            1           7d1h

kafka-broker-receiver        1/1     1            1           7d1h

kafka-controller             1/1     1            1           7d1h

kafka-webhook-eventing       1/1     1            1           7d1h

pingsource-mt-adapter        0/0     0            0           7d1h

rabbitmq-broker-controller   1/1     1            1           9m4s

rabbitmq-broker-webhook      1/1     1            1           9m4s
```

Then I created a secret.
With the help of this Microsoft tool `https://red-mushroom-0f7446a0f.azurestaticapps.net/`
I managed to convert Azure Service Bus string to RabbitMQ amqp.
 
`kubectl create secret --namespace knative-eventing generic azureservicebus --from-literal=brokerURL="I PLACED THE STRING HERE"`

and then created RabbitMQ broker:

```
soareslo:~$cat create-rabbitmq-broker.yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
  name: rabbitmqbroker
  namespace: default
spec:
  # Configuration specific to this broker.
  config:
    apiVersion: v1
    kind: Secret
    name: azureservicebus
    namespace: knative-eventing
```

However as you can see, the RabbitMQ Broker is not generating the URL.

```
soareslo:~$kubectl get brokers

NAME             URL                                                                                AGE     READY   REASON

lasbroker        http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/lasbroker   7d2h    True    

rabbitmqbroker                                                                                      2m54s           

```

Below you can see the broker description without errors.

```
soareslo:~$kubectl describe broker rabbitmqbroker       

Name:         rabbitmqbroker

Namespace:    default

Labels:       <none>

Annotations:  eventing.knative.dev/broker.class: RabbitMQBroker

              eventing.knative.dev/creator: masterclient

              eventing.knative.dev/lastModifier: masterclient

API Version:  eventing.knative.dev/v1

Kind:         Broker

Metadata:

  Creation Timestamp:  2021-11-25T12:24:49Z

  Generation:          1

  Managed Fields:

    API Version:  eventing.knative.dev/v1

    Fields Type:  FieldsV1

    fieldsV1:

      f:metadata:

        f:annotations:

          .:

          f:eventing.knative.dev/broker.class:

          f:kubectl.kubernetes.io/last-applied-configuration:

      f:spec:

        .:

        f:config:

          .:

          f:apiVersion:

          f:kind:

          f:name:

          f:namespace:

    Manager:         kubectl-client-side-apply

    Operation:       Update

    Time:            2021-11-25T12:24:48Z

  Resource Version:  13195895

  UID:               003cf445-af3c-4519-8237-78e301f505f6

Spec:

  Config:

    API Version:  v1

    Kind:         Secret

    Name:         azureservicebus

    Namespace:    knative-eventing

Events:           <none>

soareslo:~$

```
 **Knative release version**
v1.0

 **Additional context**
High priority

**Comment by xtreme-sameer-vohra** [comment] 2022-03-13 20:11
Hey @andersonsoares-tomtom 
Thanks for reporting the issue. Are you able to reproduce the issue using the [RabbitMQ operator based Broker](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md#rabbitmq-operator-based-broker) ?

After a discussion in the community, we are considering [removing support for the Standalone Broker](https://github.com/knative-sandbox/eventing-rabbitmq/issues/411).

**Comment by xtreme-sameer-vohra** [comment] 2022-04-13 00:23
Hey @andersonsoares-tomtom going to close this issue since its been so long.
Please feel free to create an issue if you're still experiencing problems. In case you don't hear from someone on github, you can also reach us on [eventing-rabbitmq on Slack](https://knative.slack.com/archives/C02N2AK2K1P)

**Closed by xtreme-sameer-vohra** 2022-04-13 00:23 UTC
Labels: kind/bug
